### ISSUE TITLE
The bridge does not work if the dependency expects a Rhumsaa\Uuid\Uuid instance

### ISSUE THREAD

**Issue by jonsa** [MattKetmo/uuid-2x-bridge#1]
If the project dependency uses the 2.x branch and expects a `Rhumsaa\Uuid\Uuid` when it calls one of the named constructors. It will fail since it receives either a `Ramsey\Uuid\Uuid` or `Ramsey\Uuid\DegradedUuid` instance.

I have a working project, inspired by this one, which utilizes more of a copy-paste strategy of the `2.x` branch, which solves that problem and runs the tests successfully too.

Would you be interested in a pull request which would make this project not so tiny anymore?

**Comment by MattKetmo** [comment]
Hello,

I'm not sure to understand the issue. The static constructors in both Rhumsaa or Ramsey namespace have the same name/signature so it shouldn't be a problem. Do you have an example where it fails?

**Comment by jonsa** [comment]
Sure.

``` php
class Foo
{
    public function __construct(\Rhumsaa\Uuid\Uuid $uuid)
    {
    }
}

new Foo(\Rhumsaa\Uuid\Uuid::uuid4());
```

Will work with

``` json
{
  "require": {
    "ramsey/uuid": "^2.0"
  }
}
```

but not with

``` json
{
  "require": {
    "mattketmo/uuid-2x-bridge": "*@dev"
  }
}
```

```
Catchable fatal error: Argument 1 passed to Foo::__construct() must be an instance of Rhumsaa\Uuid\Uuid, instance of Ramsey\Uuid\DegradedUuid given
```

**Comment by MattKetmo** [comment]
Ok I see. It fails when there is a type hint on Rhumsaa in a function.
I'm interested by having a look at your solution then :)

**Comment by MattKetmo** [comment]
This would be my workaround:

``` php
class Uuid extends \Ramsey\Uuid\Uuid
{
    public static function uuid4()
    {
        $uuid = parent::uuid4();

        return new self(
            $uuid->getFieldsHex(),
            $uuid->getNumberConverter(),
            \Ramsey\Uuid\Uuid::getFactory()->getCodec()
        );
    }

    // public static function::uuid5()
    // ...
}
```

**Comment by jonsa** [comment]
It looks good to me. It works in with my project but it is only using `uuid4` and `fromString` so it's not really representing all the functionality.

You will not get the full `2.x` branch test suite to run since it utilizes static properties to emulate different environments, but I'm not sure that is desired for this kind of project anyway.
